language: go

services:
  - docker

matrix:
  include:
    - os: linux
      go: "1.10"
    - os: linux
      go: 1.10.x
    - os: linux
      go: 1.11.x
      env: LATEST_GO=1
    - os: osx
      go: 1.11.x
    - os: windows
      go: 1.11.x

go_import_path: mvdan.cc/sh

install: true

script:
  - go get -d -t ./...
  - go install ./...
  - go test ./...
    # TODO: reenable test -race on windows once TestInteractive stops failing
  - if [[ $TRAVIS_OS_NAME != "windows" ]]; then go test -short -race ./...; fi
  - shfmt -version
  - if [[ -n $LATEST_GO ]]; then diff <(echo -n) <(gofmt -d .); fi
  - if [[ -n $LATEST_GO && $TRAVIS_EVENT_TYPE == push && $TRAVIS_BRANCH == master ]]; then ./release-docker.sh; fi
