version: "{build}"

clone_folder: c:\gopath\src\mvdan.cc\sh

environment:
  GOPATH: c:\gopath

stack: go 1.10

install:
  - go version

build: false
deploy: false

test_script:
  - go get -d -t ./...
  - go install ./...
  - go test ./...
